project: mock-file-tree
version: 1.1.1
author: Joel Lefkowitz
verbose_name: Mock file tree
html_title: Mock file tree
github_url: https://github.com/JoelLefkowitz/mock-file-tree
apidoc_module_dir: src
